### PR TITLE
all arity-specific methods are broken

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
just pushed

**Comment by eparejatobes** [comment]
EdgeType needs to refer to itself in TypedGraph, otherwise you just know about it source and target. This is wrong: https://github.com/bio4j/angulillos/blob/7ca8381f7eb91c3a07bb9185edefa3e23f9f9293/src/main/java/com/bio4j/angulillos/TypedGraph.java#L216-L234

**Comment by eparejatobes** [comment]
That, or making on EdgeType class per Arity combination in TypedGraph

**Comment by eparejatobes** [comment]
There's a super-easy unsafe fix though, that could be enough

**Comment by eparejatobes** [comment]
@laughedelic doing this? if not, will do

**Comment by laughedelic** [comment]
What's your plan?

**Comment by eparejatobes** [comment]
to fix it!

**Pull request merged**
