### PR TITLE
All Element types are graph's inner classes

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic ping me if you need help here

**Comment by laughedelic** [comment]
@eparejatobes I have some more code that I haven't pushed yet. I'd like to discuss some things about it with you.

**Comment by laughedelic** [comment]
One important thing that I'm quite sure about: no matter how you refine types, use self-references, etc. if in, say, `User` you don't subclass `Vertex` inner class, then 
- `Twitter<RV,RE>.User.Vertex`
- `TypedGraph< Twitter<RV,RE>, RV,RE >.VertexType< Twitter<RV,RE>.User >.Vertex`

are the same thing. i.e. `User` doesn't have its own specific `Vertex` inner class. 

I'm fine with it. As soon as the `Vertex` is made final, nothing bad can happen with it.

**Comment by laughedelic** [comment]
Actually, taking into account all this, I don't see any advantages of this approach over what we already have in #58...

**Comment by laughedelic** [comment]
I've tried moving things from the outer interfaces to the inner-inner classes and I can say that **it doesn't help _anything_**. 

- It doesn't help to have simpler types, 
- it doesn't solve the problem with inheritors not having their own inner class (if you don't extend it explicitly), 
- and it doesn't help with the difficutly in overriding things in the inner classes.

**Pull request closed without merging**
